
DROP TABLE IF EXISTS especie;

CREATE TABLE especie (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  abbreviation VARCHAR(50) NOT NULL UNIQUE,
  common_name VARCHAR(50) NOT NULL,
  scientific_name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO especie (id, abbreviation, common_name, scientific_name) VALUES
  (1, 'JT', 'Jataí', 'Tetragosnisca angustula'),
  (2, 'EM', 'Mirim emerina', 'Plebeia emerina'),
  (3, 'PG', 'Mirim', 'Plebeia gigantea'),
  (4, 'MQ', 'Mandaçaia', 'Melipona quadrifasciata'),
  (5, 'MB', 'Guaraipo', 'Melipona bicolor'),
  (6, 'MD', 'Manduri', 'Melipona marginata'),
  (7, 'MT', 'Manduri', 'Melipona torrida'),
  (8, 'SB', 'Tubuna', 'Scaptotrigona bipunctata'),
  (9, 'SD', 'Canudo', 'Scaptotrigona depilis'),
  (10, 'MM', 'Mirim mosquito', 'Plebeia droryana');

DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO usuario (email, password_hash, created_at, updated_at) VALUES
  ('test@test.com', '$2b$12$exampleHashReplaceWithRealBcryptHashValueHere00000', NOW(), NOW());

DROP TABLE IF EXISTS meliponario;

CREATE TABLE meliponario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(255) NOT NULL,
  owner_id BIGINT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES usuario(id)
);

INSERT INTO meliponario (name, address, owner_id) VALUES
  ('Meliponario de Teste', 'Rua 1, Bairro 1, Cidade 1, Estado 1', 1);

DROP TABLE IF EXISTS status_colmeia;

CREATE TABLE status_colmeia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS colmeia;

CREATE TABLE colmeia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code INT,
  species_id BIGINT NOT NULL,
  meliponario_id BIGINT NOT NULL,
  start_date TIMESTAMPTZ,
  FOREIGN KEY (species_id) REFERENCES especie(id),
  FOREIGN KEY (meliponario_id) REFERENCES meliponario(id)
);

DROP TABLE IF EXISTS colmeia_status_historico;

CREATE TABLE colmeia_status_historico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  colmeia_id BIGINT NOT NULL,
  status_id BIGINT NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (colmeia_id) REFERENCES colmeia(id) ON DELETE CASCADE,
  FOREIGN KEY (status_id) REFERENCES status_colmeia(id)
);

/* current status per colmeia = latest row; index makes that lookup fast */
CREATE INDEX idx_colmeia_status_hist_atual
  ON colmeia_status_historico (colmeia_id, recorded_at DESC);

DROP TABLE IF EXISTS localizacao;

CREATE TABLE localizacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  colmeia_id BIGINT NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  accuracy_meters DECIMAL(5,2),
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (colmeia_id) REFERENCES colmeia(id) ON DELETE CASCADE
);

/* current location per colmeia = latest row */
CREATE INDEX idx_localizacao_atual
  ON localizacao (colmeia_id, recorded_at DESC);

DROP TABLE IF EXISTS usuario_whatsapp;

CREATE TABLE usuario_whatsapp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  phone_number VARCHAR(20) NOT NULL UNIQUE,
  display_name VARCHAR(100),
  linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

DROP TABLE IF EXISTS sessao_chat;

CREATE TABLE sessao_chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_whatsapp_id BIGINT NOT NULL,
  conversation_context JSONB NOT NULL,
  last_message_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  FOREIGN KEY (usuario_whatsapp_id) REFERENCES usuario_whatsapp(id)
);

CREATE INDEX idx_sessao_chat_usuario_whatsapp ON sessao_chat(usuario_whatsapp_id);
CREATE INDEX idx_sessao_chat_expira ON sessao_chat(expires_at);