-- Baseline schema for bombus. Mirrors the original database.sql DDL.
-- Reference/seed data is applied in later migrations; this file is schema only.

CREATE TABLE especie (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  abbreviation VARCHAR(50) NOT NULL UNIQUE,
  common_name VARCHAR(50) NOT NULL,
  scientific_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE meliponario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(255) NOT NULL,
  owner_id BIGINT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES usuario(id)
);

CREATE TABLE status_colmeia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE colmeia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code INT,
  species_id BIGINT NOT NULL,
  meliponario_id BIGINT NOT NULL,
  start_date TIMESTAMPTZ,
  FOREIGN KEY (species_id) REFERENCES especie(id),
  FOREIGN KEY (meliponario_id) REFERENCES meliponario(id)
);

CREATE TABLE colmeia_status_historico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  colmeia_id BIGINT NOT NULL,
  status_id BIGINT NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (colmeia_id) REFERENCES colmeia(id) ON DELETE CASCADE,
  FOREIGN KEY (status_id) REFERENCES status_colmeia(id)
);

-- current status per colmeia = latest row; index makes that lookup fast
CREATE INDEX idx_colmeia_status_hist_atual
  ON colmeia_status_historico (colmeia_id, recorded_at DESC);

CREATE TABLE localizacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  colmeia_id BIGINT NOT NULL,
  latitude DECIMAL(9,6) NOT NULL,
  longitude DECIMAL(9,6) NOT NULL,
  accuracy_meters DECIMAL(5,2),
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (colmeia_id) REFERENCES colmeia(id) ON DELETE CASCADE
);

-- current location per colmeia = latest row
CREATE INDEX idx_localizacao_atual
  ON localizacao (colmeia_id, recorded_at DESC);

CREATE TABLE usuario_whatsapp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  phone_number VARCHAR(20) NOT NULL UNIQUE,
  display_name VARCHAR(100),
  linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE sessao_chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_whatsapp_id BIGINT NOT NULL,
  conversation_context JSONB NOT NULL,
  last_message_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  FOREIGN KEY (usuario_whatsapp_id) REFERENCES usuario_whatsapp(id)
);

CREATE INDEX idx_sessao_chat_usuario_whatsapp ON sessao_chat(usuario_whatsapp_id);
CREATE INDEX idx_sessao_chat_expira ON sessao_chat(expires_at);
