-- Canonical reference data: species (colmeia.species_id + bot vocabulary) and colmeia statuses.

INSERT INTO especie (id, abbreviation, common_name, scientific_name) VALUES
  (1, 'JT', 'Jataí', 'Tetragosnisca angustula'),
  (2, 'EM', 'Mirim emerina', 'Plebeia emerina'),
  (3, 'PG', 'Mirim', 'Plebeia gigantea'),
  (4, 'MQ', 'Mandaçaia', 'Melipona quadrifasciata'),
  (5, 'MB', 'Guaraipo', 'Melipona bicolor'),
  (6, 'MD', 'Manduri', 'Melipona marginata'),
  (7, 'MT', 'Manduri', 'Melipona torrida'),
  (8, 'SB', 'Tubuna', 'Scaptotrigona bipunctata'),
  (9, 'SD', 'Canudo', 'Scaptotrigona depilis'),
  (10, 'MM', 'Mirim mosquito', 'Plebeia droryana');

-- Explicit ids above do not advance the GENERATED BY DEFAULT identity sequence;
-- realign it so future inserts don't collide with the seeded ids.
SELECT setval(pg_get_serial_sequence('especie', 'id'), (SELECT MAX(id) FROM especie));

-- Canonical colmeia status vocabulary (Epic 4).
INSERT INTO status_colmeia (id, name) VALUES
  (1, 'desenvolvendo'),
  (2, 'recuperando'),
  (3, 'estavel'),
  (4, 'perdida');

SELECT setval(pg_get_serial_sequence('status_colmeia', 'id'), (SELECT MAX(id) FROM status_colmeia));

-- One active chat session per WhatsApp user (Epic 6): enables an ON CONFLICT upsert on
-- read/refresh. The unique constraint's index replaces the plain lookup index above.
DROP INDEX IF EXISTS idx_sessao_chat_usuario_whatsapp;
ALTER TABLE sessao_chat ADD CONSTRAINT uq_sessao_chat_usuario_whatsapp UNIQUE (usuario_whatsapp_id);
