-- Canonical species reference data required by colmeia.species_id and the bot vocabulary.

INSERT INTO especie (id, abbreviation, common_name, scientific_name) VALUES
  (1, 'JT', 'Jataí', 'Tetragosnisca angustula'),
  (2, 'EM', 'Mirim emerina', 'Plebeia emerina'),
  (3, 'PG', 'Mirim', 'Plebeia gigantea'),
  (4, 'MQ', 'Mandaçaia', 'Melipona quadrifasciata'),
  (5, 'MB', 'Guaraipo', 'Melipona bicolor'),
  (6, 'MD', 'Manduri', 'Melipona marginata'),
  (7, 'MT', 'Manduri', 'Melipona torrida'),
  (8, 'SB', 'Tubuna', 'Scaptotrigona bipunctata'),
  (9, 'SD', 'Canudo', 'Scaptotrigona depilis'),
  (10, 'MM', 'Mirim mosquito', 'Plebeia droryana');

-- Explicit ids above do not advance the GENERATED BY DEFAULT identity sequence;
-- realign it so future inserts don't collide with the seeded ids.
SELECT setval(pg_get_serial_sequence('especie', 'id'), (SELECT MAX(id) FROM especie));
